# -*- coding: utf-8 -*-
"""Trabalho final de ciência de dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhfFap3HowJIBaGHnBC-XQULZ69JwAAZ
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/phyton trabalho/Teen_Mental_Health_Dataset.csv")

df.head()

"""##### Questão 1: Qual é a faixa etária com maior índice de uso de redes sociais? Além disso, considerando apenas esse grupo específico, qual plataforma apresenta maior popularidade: Instagram ou TikTok?

"""

media_horas_por_idade = df.groupby('age')['daily_social_media_hours'].mean()
idade_maior_uso = media_horas_por_idade.idxmax()
horas_maior_uso = media_horas_por_idade.max()

print(f"1. A idade com maior uso médio de redes sociais é {idade_maior_uso} anos (Média: {horas_maior_uso:.2f} horas/dia).")

df_idade_especifica = df[df['age'] == idade_maior_uso]

plataformas_contagem = df_idade_especifica['platform_usage'].value_counts()

print(f"\n2. Preferência de plataforma entre os jovens de {idade_maior_uso} anos:")
print(plataformas_contagem)

insta_count = plataformas_contagem.get('Instagram', 0)
tiktok_count = plataformas_contagem.get('TikTok', 0)

if insta_count > tiktok_count:
    print("\nConclusão: O Instagram é mais popular que o TikTok nesse grupo específico.")
elif tiktok_count > insta_count:
    print("\nConclusão: O TikTok é mais popular que o Instagram nesse grupo específico.")
else:
    print("\nConclusão: Instagram e TikTok possuem exatamente a mesma popularidade nesse grupo.")

"""#####Questão 2: Qual a média de depressão e ansiedade das pessoas que tem maior nível de dependência em telas?"""

maior_dependencia = df['addiction_level'].max()

df_maior_dependencia = df[df['addiction_level'] == maior_dependencia]

media_ansiedade = df_maior_dependencia['anxiety_level'].mean()

taxa_depressao = df_maior_dependencia['depression_label'].mean() * 100
print(f"Resultados para o grupo com nível de dependência máximo ({maior_dependencia})")
print(f" Média de Ansiedade (anxiety_level): {media_ansiedade:.2f}")
print(f" Incidência de Depressão: {taxa_depressao:.2f}% dos jovens neste grupo possuem depressão.")

"""##### Questão 3: O impacto das redes sociais (nível de stress,performace academica, atividades físicas e horas de sono) afeta qual gênero em maior quantidade?"""

impacto_total = {}

for genero in df['gender'].unique():
    df_genero = df[df['gender'] == genero]

correlacoes = df_genero[['daily_social_media_hours', 'stress_level', 'academic_performance', 'physical_activity', 'sleep_hours']].corr()

impacto = correlacoes['daily_social_media_hours'].drop('daily_social_media_hours')

impacto_total[genero] = impacto.abs().sum()

genero_mais_impactado = max(impacto_total, key=impacto_total.get)
maior_valor = impacto_total[genero_mais_impactado]
print(f"De acordo com a tabela, o gênero mais impactado é: {genero_mais_impactado}")
print(f"Soma total das correlações (nível de impacto): {maior_valor:.2f}")

"""##### Questão 4: Qual plataforma as pessoas usam mais antes de dormir?"""

tempo_medio_antes_dormir = df.groupby('platform_usage')['screen_time_before_sleep'].mean()

plataforma_campea = tempo_medio_antes_dormir.idxmax()
maior_tempo = tempo_medio_antes_dormir.max()

for plataforma, tempo in tempo_medio_antes_dormir.items():
    print(f"{plataforma}: {tempo:.2f} horas")

print(f"\nConclusão: A plataforma mais usada antes de dormir é o {plataforma_campea}, com uma média de {maior_tempo:.2f} horas.")

"""##### Questão 5: Qual a média de sono das pessoas que mais e menos utilizam as redes sociais antes de dormir?"""

import pandas as pd
import matplotlib.pyplot as plt

max_tempo_tela = df['screen_time_before_sleep'].max()
min_tempo_tela = df['screen_time_before_sleep'].min()
grupo_mais_usa = df[df['screen_time_before_sleep'] == max_tempo_tela]
grupo_menos_usa = df[df['screen_time_before_sleep'] == min_tempo_tela]

media_sono_mais_usa = grupo_mais_usa['sleep_hours'].mean()
media_sono_menos_usa = grupo_menos_usa['sleep_hours'].mean()

print("--- Relação entre Uso de Telas antes de Dormir e Horas de Sono ---")
print(f"Maior uso ({max_tempo_tela}h de tela): dorme em média {media_sono_mais_usa:.2f} horas.")
print(f"Menor uso ({min_tempo_tela}h de tela): dorme em média {media_sono_menos_usa:.2f} horas.\n")

categorias = ['MAIS usam antes de dormir', 'MENOS usam antes de dormir']
medias_sono = [media_sono_mais_usa, media_sono_menos_usa]
cores = ['#d9534f', '#5cb85c']

plt.figure(figsize=(8, 6))
barras = plt.bar(categorias, medias_sono, color=cores, width=0.6)
plt.title('Comparação: Horas de Sono vs. Uso de Telas Antes de Dormir', fontsize=14, fontweight='bold')
plt.ylabel('Média de Horas de Sono', fontsize=12)
for barra in barras:
    altura = barra.get_height()
    plt.text(barra.get_x() + barra.get_width()/2., altura + 0.1,
             f'{altura:.2f}h', ha='center', va='bottom', fontsize=12, fontweight='bold')
    plt.ylim(0, max(medias_sono) + 2) # Dá um espaço extra no topo para o número não cortar
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""#####Questão 6: Qual o nivel de atividade fisica das pessoas que mais utilizam redes sociais?"""

max_horas_redes = df['daily_social_media_hours'].max()

grupo_mais_usa_redes = df[df['daily_social_media_hours'] == max_horas_redes]

media_atividade_fisica = grupo_mais_usa_redes['physical_activity'].mean()

print("Atividade Física das Pessoas que MAIS Usam Redes Sociais ")
print(f" Maior tempo de uso diário registrado na base: {max_horas_redes} horas.")
print(f" Média de atividade física desse grupo: {media_atividade_fisica:.2f}")

"""#####Questão 7: Qual a média de interação social por idade?"""

import pandas as pd
import matplotlib.pyplot as plt

mapa_interacao = {'low': 1, 'medium': 2, 'high': 3}
df['social_interaction_numeric'] = df['social_interaction_level'].map(mapa_interacao)

media_interacao_idade = df.groupby('age')['social_interaction_numeric'].mean()

idade_mais_interacao = media_interacao_idade.idxmax()
idade_menos_interacao = media_interacao_idade.idxmin()

valor_max = media_interacao_idade.max()
valor_min = media_interacao_idade.min()

print("--- Nível de Interação Social por Faixa Etária ---")
print(f"Idade com MAIOR interação social: {idade_mais_interacao} anos (Média: {valor_max:.2f})")
print(f"Idade com MENOR interação social: {idade_menos_interacao} anos (Média: {valor_min:.2f})\n")

plt.figure(figsize=(10, 6))
barras = plt.bar(media_interacao_idade.index, media_interacao_idade.values, color='#8E44AD', edgecolor='black')
for i, idade in enumerate(media_interacao_idade.index):
    if idade == idade_mais_interacao:
        barras[i].set_color('#27AE60')
        barras[i].set_edgecolor('black')
    elif idade == idade_menos_interacao:
        barras[i].set_color('#E74C3C')
        barras[i].set_edgecolor('black')
        plt.title('Média de Interação Social por Idade', fontsize=14, fontweight='bold')
plt.xlabel('Idade (Anos)', fontsize=12)
plt.ylabel('Nível Médio (1=Baixo, 2=Médio, 3=Alto)', fontsize=12)
plt.xticks(media_interacao_idade.index)
for barra in barras:
    altura = barra.get_height()
    plt.text(barra.get_x() + barra.get_width()/2., altura + 0.05,
             f'{altura:.2f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
    plt.ylim(0, 3.5)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""#####Questão 8: Qual o tempo de tela das pessoas que tem o nivel de estresse acima de 7?"""

df_alto_estresse = df[df['stress_level'] > 7]

media_horas_diarias = df_alto_estresse['daily_social_media_hours'].mean()
media_tela_antes_dormir = df_alto_estresse['screen_time_before_sleep'].mean()

print("Tempo de Tela (Estresse acima de 7)")
print(f" Média de tempo diário nas redes sociais: {media_horas_diarias:.2f} horas")
print(f" Média de tempo de tela antes de dormir: {media_tela_antes_dormir:.2f} horas")